### ISSUE TITLE
cmd_vel problem

### ISSUE THREAD

**Issue by yerynkim-jazz** [Atharva-05/unitree_ros2_sim#3]
Hello Atharva!

I'm trying to implement your repository, but controlling the robot with cmd_vel commands doesn't work. 
For example, these commands doesn't move the robot:
ros2 run teleop_twist_keyboard teleop_twist_keyboard
ros2 topic pub /cmd_vel geometry_msgs/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.2}}"

There is one publisher, but there is no subscribers. 
And it seems like there is a problem with the robot interface.

Could you please give some assistance?

Best regards,
Yeryn

**Comment by Atharva-05** [comment]
Hello Yeryn,

Did you follow the steps in points 2 and 4 in the readme? (The navigation command in point 3 launches nav2, it can be skipped while testing the /cmd_vel interface).

Once the robot is standing up and has switched to mode 5 (after pressing 2, and then 5 in the `junior_ctrl` node tab) it should respond to velocity commands on the /cmd_vel topic. Please wait for all the joint controllers to load before running any command. This can be verified from the logs in the gazebo terminal window.

If this is not happening, could you report what the state of the system is? Please share screenshots of the gazebo and junior_crtl terminal windows along with the gazebo GUI.

Thanks

**Comment by yerynkim-jazz** [comment]
Thank you so much!
